### ISSUE TITLE
Very small picture when reading image from NEF file

### ISSUE THREAD

**Issue by mizalewski** [dlemstra/Magick.WASM#7]
I tried to use Magick.WASM to resize NEF files (Nikon RAW camera files) but output pictures are really small (160x120 pixels). I have done some trials with just converting NEF files to JPG without any resize but output files still were small - 160x120 pixels. It looks like Magick.WASM only read thumbnail from NEF files.

I tried also CR2 files from Canon 5D Mark III and IV. Magick.WASM works as expected for those files. JPGs are also resized without any issue.

I have done tests on command line version of ImageMagick but without built-in RAW delegates (using ufraw-batch). Cmd line version converted NEF files correctly to JPG with full resolution.

For tests I used below files (2 NEFs and 1 CR2):
https://drive.google.com/file/d/1yut_Z-NI2VR7XfIfY7MBQWH3Pq-R5Fb0/view?usp=sharing

RAWs can also be downloaded from (under "Sample RAW Images" header):
NEF: https://www.photographyblog.com/reviews/nikon_d780_review/sample_images
CR2: https://www.photographyblog.com/reviews/canon_eos_5d_mark_iii_review/sample_images

Here is also code I used in web worker to resize pictures (resize is commented out in below code):
```typescript
import {ImageMagick, initializeImageMagick} from '@imagemagick/magick-wasm'
import {MagickFormat} from '@imagemagick/magick-wasm/magick-format'
import {logInfoToConsole} from '../../shared/logInfoToConsole'
import {IImageMagickConfig} from './IImageMagickConfig'

const ctx: Worker = self as any

class ImageMagickWrapper {
  private initialized: boolean

  public async resize(sourceImage: ArrayBuffer, config: IImageMagickConfig): Promise<Blob> {
    await this.initializeIfNeeded()

    let output = null
    logInfoToConsole(`Source image size: ${sourceImage.byteLength / 1024} KB`)
    await ImageMagick.read(new Uint8Array(sourceImage), async (image) => {
      // image.resize(config.maxWidth, config.maxHeight)
      // image.quality = config.quality

      await image.write((data) => {
        logInfoToConsole(`Resized image size: ${data.length / 1024} KB`)
        output = data
        return Promise.resolve()
      }, MagickFormat.Jpeg)
    })

    return new Blob([output])
  }

  private async initializeIfNeeded() {
    logInfoToConsole('initializeIfNeeded')
    if (this.initialized) {
      return
    }

    await initializeImageMagick()

    this.initialized = true
  }
}

const imageMagickWrapper = new ImageMagickWrapper()

ctx.onmessage = async (e: MessageEvent) => {
  const {sourceImage, config} = e.data as {sourceImage: ArrayBuffer; config: IImageMagickConfig}

  const resizedImage = await imageMagickWrapper.resize(sourceImage, config)
  ctx.postMessage({blob: resizedImage})
}

// export default null as any;
```

**Comment by dlemstra** [comment]
The problem is that ImageMagick cannot detect the format from the header for the `NEF` format. You will need to specify the format in the `MagickReadSettings`.
